name: test
on:
  push:

jobs:
  test:
    name: annotate
    runs-on: ubuntu-latest
    steps:
    - name: Issue error command with STDOUT
      run: python3 -c "print('::error file=.github/workflows/test.yml,line=1::from stdout')"

    - name: Issue error command with STDERR
      run: python3 -c "import sys; print('::error file=.github/workflows/test.yml,line=1::from stderr', file=sys.stderr)"
