name: test
on:
  push:

jobs:
  test:
    name: annotate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo ::error file=.github/workflows/test.yml,line=1::test2
